[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = [
  "-C", "link-arg=-static",
  "-C", "link-arg=-static-libgcc",
  "-C", "link-arg=-static-libstdc++",
  "-C", "link-arg=-lstdc++",
]

